---
title: Cats that are allowed to go outside are terrible for the environment; they
  devastate biodiversity. The domesticated cat is an invasive species that increases
  the effects of global warming, because birds are key to protecting ecosystems from
  the stresses of climate change
id: '39'
cited_urls:
- url: https://www.motherjones.com/environment/2011/07/cats-tnr-birds-feral/#apocalypse_meow
  quotes: []
  challenges: 
new_cited_url: 
topics:
- Cats
- Environment
- Global warming
explanations:
  '1':
    id: 1
    text: "In one study, catbirds primarily died from predators, the plurality of
      which were cats:\r\n\r\n> The main determining factor was predation, which accounted
      for 79 percent of juvenile catbird deaths within the team’s three suburban study
      sites. Nearly half (47 percent) of the deaths were attributed to domestic cats
      in Opal Daniels and Spring Park. The deaths were either witnessed by the scientists
      or determined to be cat-related by the condition of the fledgling’s remains,
      such as a decapitated bird with the body left uneaten—defining characters of
      a cat kill.\r\n\r\nBirds are important for protecting from the shocks of climate
      change - by, for example, eating invasive insect pests:\r\n\r\n> Excluding birds
      caused a greater increase in herbivorous arthropod abundance than excluding
      bats, leading to increased coffee leaf damage.\r\n\r\nRather than euthanizing
      feral cats, cat lovers have advocated for trapping, sterilizing and releasing
      (TNR) and generally prize cat life above native biodiversity:\r\n\r\n> Cat groups
      are trying to reinstate TNR in Los Angeles (where it failed miserably in the
      past) and make it illegal to remove ferals from a wildlife refuge in South Florida,
      where the cats have taken a major toll on an endangered woodrat.\r\n\r\nThis
      is a common failure state of animal welfare groups.\r\n\r\n> This action was
      opposed vociferously by animal welfare groups who were concerned about cruelty
      during the poisoning. As a young and idealistic conservationist I was shocked
      that such an important program could be halted by opponents who concluded they
      would rather allow the extinction of all 17 endangered endemics that condone
      the poisoning of rabbits. The island's condition deteriorated for 12 more years
      until 1986 when the rabbits were finally eradicated by a well-executed poisoning
      program."
    quote_urls:
    - https://insider.si.edu/2011/03/alarming-number-of-fledgling-suburban-catbirds-fall-prey-to-domestic-cats-study-finds
    - https://esajournals.onlinelibrary.wiley.com/doi/10.1890/13-1012.1
    - https://www.motherjones.com/environment/2011/07/cats-tnr-birds-feral/#apocalypse_meow
    - https://conbio.onlinelibrary.wiley.com/doi/abs/10.1111/j.1523-1739.1990.tb00096.x
