---
title: Cats that are allowed to go outside are terrible for the environment; they
  devastate biodiversity. The domesticated cat is an invasive species that increases
  the effects of global warming, because birds are key to protecting ecosystems from
  the stresses of climate change.
id: '39'
cited_urls:
- url: https://www.motherjones.com/environment/2011/07/cats-tnr-birds-feral/#apocalypse_meow
  quotes: []
  challenges: 
new_cited_url: 
topics:
- Cats
- Environment
- Global warming
arguments: {}
